/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue_user_borne;

import Config.ConfigGlobale;
import classes.Utilisateur;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class LouerVelo extends javax.swing.JFrame {

    public ControleurLouerVelo ctrlLV;
 
    public LouerVelo(ControleurLouerVelo aThis) {
        initComponents();
        ctrlLV = aThis; 
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelMenu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ButtonLouer = new javax.swing.JButton();
        ButtonRendre = new javax.swing.JButton();
        ButtonAccueil = new javax.swing.JButton();
        LabelMenu2 = new javax.swing.JLabel();
        LabelImageNemoVelo = new javax.swing.JLabel();
        LabelCarte = new javax.swing.JLabel();
        LabelRecupVelo = new javax.swing.JLabel();
        LabelRemerciement = new javax.swing.JLabel();
        LabelBienvenue = new javax.swing.JLabel();

        LabelMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMenu.setForeground(new java.awt.Color(136, 212, 29));
        LabelMenu.setText("Menu");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nemo velo");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(null);

        ButtonLouer.setText("Louer un vélo");
        ButtonLouer.setEnabled(false);
        jPanel1.add(ButtonLouer);
        ButtonLouer.setBounds(20, 40, 162, 70);

        ButtonRendre.setText("Rendre un vélo");
        ButtonRendre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRendreActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonRendre);
        ButtonRendre.setBounds(20, 110, 162, 70);
        ButtonRendre.getAccessibleContext().setAccessibleName("Rendre un velo");

        ButtonAccueil.setText("Accueil");
        ButtonAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAccueilActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonAccueil);
        ButtonAccueil.setBounds(20, 180, 162, 70);

        LabelMenu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMenu2.setForeground(new java.awt.Color(136, 212, 29));
        LabelMenu2.setText("Menu");
        jPanel1.add(LabelMenu2);
        LabelMenu2.setBounds(77, 13, 38, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 110, 198, 268);

        LabelImageNemoVelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue_user_borne/velonemo.JPG"))); // NOI18N
        getContentPane().add(LabelImageNemoVelo);
        LabelImageNemoVelo.setBounds(10, 10, 185, 72);

        LabelCarte.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelCarte.setText("1) Insérez votre carte");
        getContentPane().add(LabelCarte);
        LabelCarte.setBounds(240, 150, 270, 29);

        LabelRecupVelo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelRecupVelo.setText("2) Recupérez le velo : ");
        getContentPane().add(LabelRecupVelo);
        LabelRecupVelo.setBounds(240, 220, 370, 29);

        LabelRemerciement.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelRemerciement.setText("3) Merci et bonne route !");
        getContentPane().add(LabelRemerciement);
        LabelRemerciement.setBounds(240, 290, 350, 29);

        LabelBienvenue.setBackground(new java.awt.Color(255, 255, 255));
        LabelBienvenue.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LabelBienvenue.setForeground(new java.awt.Color(136, 212, 29));
        LabelBienvenue.setText("Louer un vélo");
        LabelBienvenue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(LabelBienvenue);
        LabelBienvenue.setBounds(300, 20, 250, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonRendreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRendreActionPerformed
        ctrlLV.RendrePerformed();
    }//GEN-LAST:event_ButtonRendreActionPerformed

    private void ButtonAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAccueilActionPerformed
        ctrlLV.AccueilPerformed();
    }//GEN-LAST:event_ButtonAccueilActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAccueil;
    private javax.swing.JButton ButtonLouer;
    private javax.swing.JButton ButtonRendre;
    private javax.swing.JLabel LabelBienvenue;
    private javax.swing.JLabel LabelCarte;
    private javax.swing.JLabel LabelImageNemoVelo;
    private javax.swing.JLabel LabelMenu;
    private javax.swing.JLabel LabelMenu2;
    private javax.swing.JLabel LabelRecupVelo;
    private javax.swing.JLabel LabelRemerciement;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    void Louer() {

        // Début de la location
        int idCarte = Integer.parseInt(JOptionPane.showInputDialog("Numéro carte abonnée ?"));
        Utilisateur user = null;
        for (Utilisateur s : ConfigGlobale.utilisateurs) {
            if(s.getFk_id_carte()==idCarte){
                user = s;
                break;
            }
        }
        if(user != null && user.getFk_id_velo()==-1){
            LabelCarte.setForeground(Color.green);
            ctrlLV.locationVelo(user);
            LabelRecupVelo.setForeground(Color.green);
            LabelRemerciement.setForeground(Color.green);
        } else {
            LabelCarte.setForeground(Color.red);
        }
    }
    
    public void messageInfo(String message){
        JOptionPane.showMessageDialog(rootPane, message);
    }
}
