/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue_user_borne;

import java.awt.Color;
import javax.swing.JOptionPane;

public class RendreVelo extends javax.swing.JFrame {

    public ControleurRendrevelo ctrlRV;

    public RendreVelo(ControleurRendrevelo aThis) {
        initComponents();
        ctrlRV = aThis;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelImageNemoVelo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ButtonLouer = new javax.swing.JButton();
        ButtonRendre = new javax.swing.JButton();
        ButtonAccueil = new javax.swing.JButton();
        LabelMenu = new javax.swing.JLabel();
        LabelImageNemoVelo = new javax.swing.JLabel();
        LabelBienvenue = new javax.swing.JLabel();
        LabelCarte = new javax.swing.JLabel();
        LabelRecupVelo = new javax.swing.JLabel();
        LabelRemerciement = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nemo velo");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        LabelImageNemoVelo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue_user_borne/velonemo.JPG"))); // NOI18N
        getContentPane().add(LabelImageNemoVelo1);
        LabelImageNemoVelo1.setBounds(10, 10, 185, 72);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(null);

        ButtonLouer.setText("Louer un vélo");
        ButtonLouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLouerActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonLouer);
        ButtonLouer.setBounds(20, 40, 162, 70);

        ButtonRendre.setText("Rendre un vélo");
        ButtonRendre.setEnabled(false);
        jPanel1.add(ButtonRendre);
        ButtonRendre.setBounds(20, 110, 162, 70);
        ButtonRendre.getAccessibleContext().setAccessibleName("Rendre un velo");

        ButtonAccueil.setText("Accueil");
        ButtonAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAccueilActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonAccueil);
        ButtonAccueil.setBounds(20, 180, 162, 70);

        LabelMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMenu.setForeground(new java.awt.Color(136, 212, 29));
        LabelMenu.setText("Menu");
        jPanel1.add(LabelMenu);
        LabelMenu.setBounds(77, 13, 38, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 110, 198, 268);
        getContentPane().add(LabelImageNemoVelo);
        LabelImageNemoVelo.setBounds(10, 369, 0, 0);

        LabelBienvenue.setBackground(new java.awt.Color(255, 255, 255));
        LabelBienvenue.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LabelBienvenue.setForeground(new java.awt.Color(136, 212, 29));
        LabelBienvenue.setText("Rendre un vélo");
        LabelBienvenue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(LabelBienvenue);
        LabelBienvenue.setBounds(290, 20, 280, 50);

        LabelCarte.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelCarte.setText("1) Insérez votre carte");
        getContentPane().add(LabelCarte);
        LabelCarte.setBounds(240, 150, 270, 29);

        LabelRecupVelo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelRecupVelo.setText("2) Reposez votre vélo ");
        getContentPane().add(LabelRecupVelo);
        LabelRecupVelo.setBounds(240, 220, 370, 29);

        LabelRemerciement.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelRemerciement.setText("3) Merci et à bientôt !");
        getContentPane().add(LabelRemerciement);
        LabelRemerciement.setBounds(240, 290, 350, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAccueilActionPerformed
        ctrlRV.AccueilPerformed();
    }//GEN-LAST:event_ButtonAccueilActionPerformed

    private void ButtonLouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLouerActionPerformed
        ctrlRV.LouerPerformed();
    }//GEN-LAST:event_ButtonLouerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAccueil;
    private javax.swing.JButton ButtonLouer;
    private javax.swing.JButton ButtonRendre;
    private javax.swing.JLabel LabelBienvenue;
    private javax.swing.JLabel LabelCarte;
    private javax.swing.JLabel LabelImageNemoVelo;
    private javax.swing.JLabel LabelImageNemoVelo1;
    private javax.swing.JLabel LabelMenu;
    private javax.swing.JLabel LabelRecupVelo;
    private javax.swing.JLabel LabelRemerciement;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
void simulationLecteurCarte() {
        String idCarte = new String();
        //Astuce pour éviter de faire une fenetre qui contrôle que ce n'est que des digits qui sont saisie
        String regex = "[0-9]+";
        do{
            idCarte = JOptionPane.showInputDialog("Numéro carte abonnée ?");
        }while(!idCarte.isEmpty() && !idCarte.matches(regex));
         
        //On vérifie que notre abonnée existe 
        if(ctrlRV.idCarteExist(idCarte)){
            LabelCarte.setForeground(Color.green);
            ctrlRV.setIdClient(new Integer(idCarte));
            ctrlRV.RendreVelo();
            LabelCarte.setForeground(Color.black);
            ctrlRV.AccueilPerformed();
        } else {
            LabelCarte.setForeground(Color.red);
            LabelCarte.setForeground(Color.black);
        }      
    }
    
    public void messageInfo(String message){
        JOptionPane.showMessageDialog(rootPane, message);
    }
}
