/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue_admin;

import javax.swing.DefaultListModel;

/**
 *
 * @author HallerCasagrande-F
 */
public class InterfaceAdminGestionComptes extends javax.swing.JPanel {

    /**
     * Creates new form InterfaceAdminGestionComptes
     */
    public InterfaceAdminGestionComptes() {
        initComponents();
        RemplissageListeComptes();
    }

    public final void RemplissageListeComptes(){
        DefaultListModel liste = new DefaultListModel();
        liste.addElement("Le compte de Jane Doe");
        liste.addElement("Le compte de John Smith");
        liste.addElement("Le compte de Kathy Green");
        listeComptes.setModel(liste);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ascenceur = new javax.swing.JScrollPane();
        listeComptes = new javax.swing.JList();
        panelEdition = new javax.swing.JPanel();

        setBackground(new java.awt.Color(102, 153, 255));
        setPreferredSize(new java.awt.Dimension(800, 400));

        ascenceur.setMaximumSize(new java.awt.Dimension(33, 80));
        ascenceur.setMinimumSize(new java.awt.Dimension(33, 80));

        listeComptes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ascenceur.setViewportView(listeComptes);

        panelEdition.setPreferredSize(new java.awt.Dimension(600, 164));
        panelEdition.setLayout(new javax.swing.BoxLayout(panelEdition, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ascenceur, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelEdition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelEdition, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(ascenceur, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ascenceur;
    private javax.swing.JList listeComptes;
    private javax.swing.JPanel panelEdition;
    // End of variables declaration//GEN-END:variables
}
