/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue_admin;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import Tools.JGoogleMapEditorPan;

/**
*
* @author Fenix
*/
public class InterfaceAdminGestion extends javax.swing.JFrame {

    /**
     *
     */
    //public static Interfaces tools = new Interfaces();
    
    /**
     *
     */
    public InterfaceAdminGestion() {
        //tools.setInterAdminGestion(this);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titreInterfaceGestion = new javax.swing.JLabel();
        menuBoutons = new javax.swing.JPanel();
        boutonUtilisateurs = new javax.swing.JButton();
        boutonComptes = new javax.swing.JButton();
        boutonCartes = new javax.swing.JButton();
        boutonStations = new javax.swing.JButton();
        boutonBornes = new javax.swing.JButton();
        boutonVelos = new javax.swing.JButton();
        panelFondInterfaceGestion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NemoVelo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        titreInterfaceGestion.setBackground(new java.awt.Color(204, 255, 255));
        titreInterfaceGestion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titreInterfaceGestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titreInterfaceGestion.setText("Interface de gestion NemoVelo");
        titreInterfaceGestion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        menuBoutons.setBackground(new java.awt.Color(51, 153, 255));

        boutonUtilisateurs.setText("Utilisateurs");
        boutonUtilisateurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonUtilisateursMouseClicked(evt);
            }
        });

        boutonComptes.setText("Comptes");
        boutonComptes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonComptesMouseClicked(evt);
            }
        });

        boutonCartes.setText("Cartes");
        boutonCartes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonCartesMouseClicked(evt);
            }
        });

        boutonStations.setText("Stations");
        boutonStations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonStationsMouseClicked(evt);
            }
        });

        boutonBornes.setText("Bornes");
        boutonBornes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonBornesMouseClicked(evt);
            }
        });

        boutonVelos.setText("Vélos");
        boutonVelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonVelosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuBoutonsLayout = new javax.swing.GroupLayout(menuBoutons);
        menuBoutons.setLayout(menuBoutonsLayout);
        menuBoutonsLayout.setHorizontalGroup(
            menuBoutonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBoutonsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(boutonUtilisateurs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonComptes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonCartes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonStations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonBornes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonVelos)
                .addGap(0, 137, Short.MAX_VALUE))
        );
        menuBoutonsLayout.setVerticalGroup(
            menuBoutonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBoutonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuBoutonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonUtilisateurs)
                    .addComponent(boutonComptes)
                    .addComponent(boutonCartes)
                    .addComponent(boutonStations)
                    .addComponent(boutonBornes)
                    .addComponent(boutonVelos))
                .addGap(19, 19, 19))
        );

        panelFondInterfaceGestion.setBackground(new java.awt.Color(102, 153, 255));
        panelFondInterfaceGestion.setPreferredSize(new java.awt.Dimension(0, 400));
        panelFondInterfaceGestion.setLayout(new javax.swing.BoxLayout(panelFondInterfaceGestion, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titreInterfaceGestion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelFondInterfaceGestion, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
            .addComponent(menuBoutons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titreInterfaceGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuBoutons, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelFondInterfaceGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonUtilisateursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonUtilisateursMouseClicked
//        InterfaceAdminGestionUtilisateurs interGestionUsers = new InterfaceAdminGestionUtilisateurs();
//        Interfaces.setInterGestionUsers(interGestionUsers);
        swapPanel(panelFondInterfaceGestion, Interfaces.getInterGestionUsers());
    }//GEN-LAST:event_boutonUtilisateursMouseClicked

    private void boutonComptesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonComptesMouseClicked
//        InterfaceAdminGestionComptes interGestionComptes = new InterfaceAdminGestionComptes();
//        Interfaces.setInterGestionComptes(interGestionComptes);
        swapPanel(panelFondInterfaceGestion, Interfaces.getInterGestionComptes());
    }//GEN-LAST:event_boutonComptesMouseClicked

    private void boutonCartesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonCartesMouseClicked
//        InterfaceAdminGestionCartes interGestionCartes = new InterfaceAdminGestionCartes();
//        Interfaces.setInterGestionCartes(interGestionCartes);
        swapPanel(panelFondInterfaceGestion, Interfaces.getInterGestionCartes());
    }//GEN-LAST:event_boutonCartesMouseClicked

    private void boutonBornesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonBornesMouseClicked
//        InterfaceAdminGestionBornes interGestionBornes = new InterfaceAdminGestionBornes();
//        Interfaces.setInterGestionBornes(interGestionBornes);
        swapPanel(panelFondInterfaceGestion, Interfaces.getInterGestionBornes());
    }//GEN-LAST:event_boutonBornesMouseClicked

    private void boutonStationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonStationsMouseClicked
//        InterfaceAdminGestionStations interGestionStations = new InterfaceAdminGestionStations();
//        Interfaces.setInterGestionStations(interGestionStations);
        swapPanel(panelFondInterfaceGestion, Interfaces.getInterGestionStations());
    }//GEN-LAST:event_boutonStationsMouseClicked

    private void boutonVelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonVelosMouseClicked
//        InterfaceAdminGestionVelos interGestionVelos = new InterfaceAdminGestionVelos();
//        Interfaces.setInterGestionVelos(interGestionVelos);
        swapPanel(panelFondInterfaceGestion, Interfaces.getInterGestionVelos());
    }//GEN-LAST:event_boutonVelosMouseClicked

    
    /**
     *
     * @param panelDeBase
     * @param newPanel
     */
    public void swapPanel(JComponent panelDeBase, JComponent newPanel){
        panelDeBase.removeAll();
        panelDeBase.add(newPanel);
        revalidate();
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boutonBornes;
    public javax.swing.JButton boutonCartes;
    public javax.swing.JButton boutonComptes;
    public javax.swing.JButton boutonStations;
    public javax.swing.JButton boutonUtilisateurs;
    public javax.swing.JButton boutonVelos;
    private javax.swing.JPanel menuBoutons;
    private javax.swing.JPanel panelFondInterfaceGestion;
    private javax.swing.JLabel titreInterfaceGestion;
    // End of variables declaration//GEN-END:variables
}
