/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue_admin;

import javax.swing.ListModel;
import javax.swing.event.ListDataListener;

/**
 *
 * @author HallerCasagrande-F
 */
public class InterfaceAdminGestionUtilisateurs extends javax.swing.JPanel {

    /**
     * Creates new form InterfaceAdminGestionUtilisateurs
     */
    public InterfaceAdminGestionUtilisateurs() {
        initComponents();
        /*jList1.setModel(new ListModel(){

            @Override
            public int getSize() {
                return 10;
            }

            @Override
            public Object getElementAt(int index) {
                return "Coucou";
            }

            @Override
            public void addListDataListener(ListDataListener l) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void removeListDataListener(ListDataListener l) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        jList1.clearSelection();*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEditionUtilisateurs = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        ascenceurUtilisateurs = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(102, 153, 255));
        setPreferredSize(new java.awt.Dimension(800, 400));

        jToggleButton1.setText("jToggleButton1");

        javax.swing.GroupLayout panelEditionUtilisateursLayout = new javax.swing.GroupLayout(panelEditionUtilisateurs);
        panelEditionUtilisateurs.setLayout(panelEditionUtilisateursLayout);
        panelEditionUtilisateursLayout.setHorizontalGroup(
            panelEditionUtilisateursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditionUtilisateursLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jToggleButton1)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        panelEditionUtilisateursLayout.setVerticalGroup(
            panelEditionUtilisateursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditionUtilisateursLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        ascenceurUtilisateurs.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ascenceurUtilisateurs, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelEditionUtilisateurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEditionUtilisateurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ascenceurUtilisateurs, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ascenceurUtilisateurs;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel panelEditionUtilisateurs;
    // End of variables declaration//GEN-END:variables
}
